### PR TITLE
vnode cache: avoid recycling a revoked node

### PR DESCRIPTION
**Pull request by catwell**
Follow-up to osxfuse/kext#5.

### CODE REVIEW

**Comment by gislan** [comment]
What is the status of this PR? I just run into this issue myself and this would fix the problem for me.

**Comment by catwell** [comment]
From my point of view: waiting for review by someone from the OSXFUSE project.

**Comment by gislan** [comment]
@bfleischer @unsound Any chance one of you could take a look at approve this PR?

Thanks!

**Comment by bfleischer** [comment]
I will look into it for version 3.6.0, which I plan on releasing shortly after Apple makes the first Developer Preview of macOS 10.13 available.

Sorry for the long wait. So far only @catwell seems to have run into this issue. I have not received additional bug reports linked to this issue.

Since the time I can spend on FUSE is somewhat limited I need to prioritize. Issues that I can reproduce and seem to be more widespread get a higher priority. This is what happened here. 

If you are interested in the current state of the FUSE project see https://groups.google.com/d/msg/osxfuse-group/BPIHlQMq6Gk/iVrud_gEKQAJ. The post is roughly one year old but it still holds true today.

**Comment by gislan** [comment]
Thanks Benjamin!

As I mentioned earlier I'm running into this issue as well so that's a second bug report. Unfortunately I can't easily share a repro case since my setup is rather complicated. If it helps I can try writing a simple daemon that reproduces it to demonstrate this PR solves the issue. Would that be helpful or are you OK merging this without a dedicated repro case?

Thanks a lot for all your work on OSXFUSE and thanks Pierre for this fix!

**Comment by catwell** [comment]
For what it's worth, we use this patch in production on thousands of installs, so it appears to kind of work. :)

Re. the state of OSXFUSE I think my company tried to get in touch at the time, but I don't know how it turned out.

**Comment by bfleischer** [comment]
> Re. the state of OSXFUSE I think my company tried to get in touch at the time, but I don't know how it turned out.

I don't remember having been contacted by Lima, nor could I find an email in my inbox. Do you know how your company tried to contact me?

**Comment by catwell** [comment]
I think that would have been by email. Sadly the person who I thought did that left the company in the meantime. I will try to talk about it internally again and get back to you.

**Comment by ericjperry** [comment]
Hello all, thank you for putting together this fix as I was having what looks like the same issue, and it appears that upgrading to 3.6.0 resolves the issue.

I have a quick question regarding workarounds, is it possible with any configuration items to work around this issue in the meantime (or if one of my deployments/customers cannot upgrade as soon as the next release is cut)? I tried setting the `novncache` flag in hopes that turning off the vnode name cache would help but it doesn't appear to have any affect. Any thoughts?

**Pull request merged**
